### PR TITLE
Common/common vfx dust

### PR DESCRIPTION
**Pull request by Omnielement**
add 6 knids of VFXDusts

### CODE REVIEW

**Comment by Setnour6** [comment]
I tested this branch and master, and when I used both the VFX Generator and the Lantern Bomb Remote Control, it works on the master branch but crashes on this branch.

**Comment by Omnielement** [comment]
> I tested this branch and master, and when I used both the VFX Generator and the Lantern Bomb Remote Control, it works on the master branch but crashes on this branch.

how to crash?

**Comment by Setnour6** [comment]
> how to crash?

When I left-click with the Lantern Bomb Remote Control, the lantern effects start, but when one of them starts to explode, the game freezes and closes by itself. Right-clicking with the Lantern Bomb Remote Control also causes the game to freeze and close. No flame VFX appears at all.
When I left-click with the VFX Generator, the game immediately freezes and closes.

**Review by Setnour6 — APPROVED** [review]
Great job! They look very nice.

**Pull request merged**
