### PR TITLE
Myth/entities hotfix1

### PR DESCRIPTION
**Pull request by Omnielement**
old contents update and bugs fixed.

### CODE REVIEW

**Review by Setnour6 — CHANGES_REQUESTED** [review]
- Corrupted Moth's wings move too fast.
- Tusk Biome's background disappears when the player is standing on the far side of the tusk arena, and flying on the same level. The entire biome background should continue to display since the entire subworld contains the biome only anyways.
- The tusk biome background changes has the huge tusks close to the platform and blocks most of the background when the player is on the left.
image


**Concerns**: MothEye (Ommateum of the Moth) is somehow broken. See if you can find out why the effects are not working.

I can't remember anything else that I tested but they were good.

**Comment by Omnielement** [comment]
> Requesting changes for the following:
> 
> * Corrupted Moth's wings move too fast.
> * Tusk Biome's background disappears when the player is standing on the far side of the tusk arena, and flying on the same level. The entire biome background should continue to display since the entire subworld contains the biome only anyways.
> * The tusk biome background changes has the huge tusks close to the platform and blocks most of the background when the player is on the left.
>   image
> 
> **Concerns**: MothEye (Ommateum of the Moth) is somehow broken. See if you can find out why the effects are not working.
> 
> I can't remember anything else that I tested but they were good.

Moth's wing flapping slow look strange, but when I increased the flapping frequency enormously, everything became better.

**Comment by Setnour6** [comment]
> > Requesting changes for the following:
> > 
> > * Corrupted Moth's wings move too fast.
> > * Tusk Biome's background disappears when the player is standing on the far side of the tusk arena, and flying on the same level. The entire biome background should continue to display since the entire subworld contains the biome only anyways.
> > * The tusk biome background changes has the huge tusks close to the platform and blocks most of the background when the player is on the left.
> >   image
> > 
> > **Concerns**: MothEye (Ommateum of the Moth) is somehow broken. See if you can find out why the effects are not working.
> > I can't remember anything else that I tested but they were good.
> 
> Moth's wing flapping slow look strange, but when I increased the flapping frequency enormously, everything became better.

The flapping speed still looked okay to me. 

There was also another thing I noticed which was the shield health, but it stays on the Corrupted Moth even after the 4D cube attack.

**Review by Setnour6 — CHANGES_REQUESTED** [review]
- Spine Gun does not work properly. I just remembered that now after testing. Given the time, this can be done in a future commit.
- Corrupted Moth's shield should still show when it doesn't do it's moth matrix if it still has health. You can make a new variable called `shieldLightVisual` that functions as `lightVisual` but for the shield only, or you can do it in any other way.

**Concerns:**
- Moth Yoyo and some other items are removed from the Corrupted Moth drop table. Do you plan to move them to another drop table, or maybe have them craftable or obtained in another way?

**Review by Setnour6 — CHANGES_REQUESTED** [review]
The moth shield did not seem to change during gameplay, still not appearing when corrupted moth is doing its normal attacks when it has health.

I am also concerned about the world tusk puzzle spawning underground. We need to add a way to either have the player teleport to the puzzle directly, or make an alternative to access the tusk subworld portal as a player would.

If you want, we can revert the shield code logic to before the shield health existed, but keep the new textures and other changes.

**Comment by Omnielement** [comment]
> The moth shield did not seem to change during gameplay, still not appearing when corrupted moth is doing its normal attacks when it has health.
> 
> I am also concerned about the world tusk puzzle spawning underground. We need to add a way to either have the player teleport to the puzzle directly, or make an alternative to access the tusk subworld portal as a player would. I recall The Tusk being a pre-hardmode boss and teleportation options to the cursor or specific area (the puzzle) are limited during pre-hardmode.
> 
> If you want, we can revert the shield code logic to before the shield health existed, but keep the new textures and other changes.

The shield was set to only appear during the moth release 4D cube to the end of weapon matrix.

**Comment by Setnour6** [comment]
> > The moth shield did not seem to change during gameplay, still not appearing when corrupted moth is doing its normal attacks when it has health.
> > I am also concerned about the world tusk puzzle spawning underground. We need to add a way to either have the player teleport to the puzzle directly, or make an alternative to access the tusk subworld portal as a player would. I recall The Tusk being a pre-hardmode boss and teleportation options to the cursor or specific area (the puzzle) are limited during pre-hardmode.
> > If you want, we can revert the shield code logic to before the shield health existed, but keep the new textures and other changes.
> 
> The shield was set to only appear during the moth release 4D cube to the end of weapon matrix. And the puzzle will only exist in the surface, so it's easy to find.

The problem is that the shield will still exist but will be invisible; it looks and sounds weird when the corrupted moth is attacked with the shield active but the shield does not appear.
At the end of the moth weapons attack, if the shield had health left, the shield would still faintly appear but the moth would take damage as normal.
What I wanted was the shield display to match the existing behavior and code logic.

I also created a new world just now and the tusk puzzle generates underground instead of the surface.
image

**Comment by Omnielement** [comment]
> The problem is that the shield will still exist but will be invisible; it looks and sounds weird when the corrupted moth is attacked with the shield active but the shield

I think it was completely solved.

**Comment by Setnour6** [comment]
> > The problem is that the shield will still exist but will be invisible; it looks and sounds weird when the corrupted moth is attacked with the shield active but the shield
> 
> I think it was completely solved.

I guess I can approve the Pull Request since you find it solved.

**Review by Setnour6 — APPROVED** [review]

**Pull request merged**
