### PR TITLE
Reimplement AssetReplace Module Functions

### PR DESCRIPTION
**Pull request by Setnour6**
This PR adds the functions of AssetReplace back to Everglow.

I had to move the UI replacement assets to Everglow.Function so they can be read from EverglowClientConfig.

### CODE REVIEW

**Comment by Cyrillya** [comment]
I'm going to do some 1.4.4 compatibility patches. And thank you for reimplementing it

**Comment by Cyrillya** [comment]
TODO: Everglow resource bar replacements. Waiting for sprites

**Comment by Setnour6** [comment]
> I'm going to do some 1.4.4 compatibility patches. And thank you for reimplementing it

You're welcome!

**Comment by Felixyang777** [comment]
Where is this branch?I can't find it in the VS so that I can't review it.
And one more question: Is this PR important? Cuz actually I don't know what it does.

**Comment by Setnour6** [comment]
> Where is this branch?I can't find it in the VS so that I can't review it. And one more question: Is this PR important? Cuz actually I don't know what it does.

I just saw this message now. I'm not sure why GitHub didn't notify me of that.
The branch is located in the forked repository under my name: https://github.com/Setnour6/Everglow-1/tree/AssetReplace/Reimplement.
I just have the mod folder content in `ModSources` named `Everglow-1`. I haven't used it in a long time though so I am not actually sure if it can still load, unless it needs to say `Everglow` strictly without `-1` appended.

This PR adds the sound and texture replacements that Omnielement and Cyril added for Everglow 1.4.3 and the public demo. Currently, AssetReplace cannot function so this PR brings back the assets needed.

**Review by Omnielement — APPROVED** [review]

**Pull request merged**
