### PR TITLE
Master everglow.function/震动

### PR DESCRIPTION
**Pull request by Omnielement**
Legacy branch, but it provide an important function.For some reasons, it hasn't successfully merge to master.The lack of this function increasingly slow down our from standardelizing screen-shaked code.

### CODE REVIEW

**Comment by Setnour6** [comment]
The new shaker does not seem to function at all

**Review by Setnour6 — CHANGES_REQUESTED** [review]
There is some delay with the shaking from the frying pan and non-smooth shaking from the flaming dash core. I cannot test Acytaea for some reason so I merged master. 

Vortex Vanquisher thump works well though.

**Comment by shb201902040125** [comment]
> There is some delay with the shaking from the frying pan and non-smooth shaking from the flaming dash core. I cannot test Acytaea.
> 
> Vortex Vanquisher thump works though.



> frying pan

This is because the starting point of the jolt is the hit enemy monster, not the player, and there is a spread time.
dashCore does not use this system

**Comment by Setnour6** [comment]
> > There is some delay with the shaking from the frying pan and non-smooth shaking from the flaming dash core. I cannot test Acytaea.
> > Vortex Vanquisher thump works though.
> 
> > frying pan
> 
> This is because the starting point of the jolt is the hit enemy monster, not the player, and there is a spread time. dashCore does not use this system

This is the frying pan shaking delay:
dotnet_oEWcPgeIGS
I tested it again and all effects work smoother for me, but Frying Pan still seems to have the delay there, except for when I activate the big shake from moving close and fast to one of the target dummies.

**Comment by Omnielement** [comment]
> > > There is some delay with the shaking from the frying pan and non-smooth shaking from the flaming dash core. I cannot test Acytaea.
> > > Vortex Vanquisher thump works though.
> > 
> > 
> > > frying pan
> > 
> > 
> > This is because the starting point of the jolt is the hit enemy monster, not the player, and there is a spread time. dashCore does not use this system
> 
> This is the frying pan shaking delay: dotnet_oEWcPgeIGS [ dotnet_oEWcPgeIGS ](https://private-user-images.githubusercontent.com/70764728/309098670-b9b4dbd7-037d-4579-90da-402c06c223a1.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyNjcwMjIsIm5iZiI6MTcwOTI2NjcyMiwicGF0aCI6Ii83MDc2NDcyOC8zMDkwOTg2NzAtYjliNGRiZDctMDM3ZC00NTc5LTkwZGEtNDAyYzA2YzIyM2ExLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAxVDA0MTg0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzMjBkZDZhZDY0YWIxN2FhYmZmZmJkZWNkNTQ0Y2FkN2E2MzlkNTkxOTU5MzZiODhmNjllNzlmOWFhNjRiMGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ecHjBpxtw53QHZ_qlAyHo7Sn2LFXTHWElTifUWCRmr8) [ ](https://private-user-images.githubusercontent.com/70764728/309098670-b9b4dbd7-037d-4579-90da-402c06c223a1.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyNjcwMjIsIm5iZiI6MTcwOTI2NjcyMiwicGF0aCI6Ii83MDc2NDcyOC8zMDkwOTg2NzAtYjliNGRiZDctMDM3ZC00NTc5LTkwZGEtNDAyYzA2YzIyM2ExLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAxVDA0MTg0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzMjBkZDZhZDY0YWIxN2FhYmZmZmJkZWNkNTQ0Y2FkN2E2MzlkNTkxOTU5MzZiODhmNjllNzlmOWFhNjRiMGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ecHjBpxtw53QHZ_qlAyHo7Sn2LFXTHWElTifUWCRmr8) I tested it again and all effects work smoother for me, but Frying Pan still seems to have the delay there, except for when I activate the big shake from moving close and fast to one of the target dummies.

The shaking effect propagates like fluctuations.If speed = 1, it will spreaded very slowly(speed value calculation was the same as 
 velocity of Projectile, NPC, etc).

**Review by Setnour6 — APPROVED** [review]
Frying Pan's shake delay is gone. I also reduced it's shake intensity since the Shake system changes seem to have made the shake more intense.

**Pull request merged**
