### PR TITLE
修改为nuget，但是仍有bug

### PR DESCRIPTION
**Pull request by Solaestas**
目前不再需要使用TmodSource作为环境了，而是直接使用nuget包，速度可能有所下降，但是比以前更加方便
现在可能会存在一些玄学bug，需要重新生成或者删除bin和obj重新编译，或者重启VS，我也不是很理解
管理module的脚本过时了，暂时不要使用，我考试完再来改

### CODE REVIEW

**Comment by Solaestas** [comment]
还需要在不同的电脑上做跟多的测试，MSBuild太玄学了

**Comment by lyc-Lacewing** [comment]
missing docs

**Review by lyc-Lacewing — CHANGES_REQUESTED** [review]
Mod building was succeeded, however mod loading successfully failed.
Seems like tModLoader recongnised the mod as it was 'built for tModLoader v0.0', hence stopped loading it.

**Comment by Setnour6** [comment]
I can't test this mod, because of Error `MSB4018, The "BuildMod" task failed unexpectedly.` in file `Solaestas.tModLoader.ModBuilder.targets` line 48.
It seems to point to `<BuildMod Condition="$(Solaestas-NotMod) != true" ModSourceDirectory="$(MSBuildProjectDirectory)\" ModName="$(AssemblyName)"`
Restarting my computer did not fix the issue.

**Comment by lyc-Lacewing** [comment]
> I can't test this mod, because of Error `MSB4018, The "BuildMod" task failed unexpectedly.` in file `Solaestas.tModLoader.ModBuilder.targets` line 48. It seems to point to `<BuildMod Condition="$(Solaestas-NotMod) != true" ModSourceDirectory="$(MSBuildProjectDirectory)\" ModName="$(AssemblyName)"` Restarting my computer did not fix the issue.

Manually delete `obj` and `bin` in Everglow/Source/Everglow/, restart VS, then it should work.

**Review by lyc-Lacewing — APPROVED** [review]

**Comment by Setnour6** [comment]
> > I can't test this mod, because of Error  in file  line 48. It seems to point to  Restarting my computer did not fix the issue.`MSB4018, The "BuildMod" task failed unexpectedly.``Solaestas.tModLoader.ModBuilder.targets``<BuildMod Condition="$(Solaestas-NotMod) != true" ModSourceDirectory="$(MSBuildProjectDirectory)\" ModName="$(AssemblyName)"`
> 
> Manually delete and in Everglow/Source/Everglow/, restart VS, then it should work.`obj``bin`

It works now! I found that this also fixes #149

**Comment by Omnielement** [comment]
It can successfully compile and load now...But fail to unload.
Generally, no problem, the unload issue has existed for a long time.

**Review by Omnielement — APPROVED** [review]

**Pull request merged**
