### PR TITLE
Shield of Vortex vanquisher

### PR DESCRIPTION
**Pull request by Felixyang777**
The shield display has been completed.
Since the code is directly modified from the vanilla code, it can be a bit unappetizing.

### CODE REVIEW

**Review by Omnielement — CHANGES_REQUESTED** [review]
I found that the hurt effect of the shield was gone.
And the shield bar over health bar will not being decrease when the shield value decreased.
The health bar still only display "life / maxLife";"life / maxLife     shield / maxShiled"will be better.

**Comment by lace-wing** [comment]
Keeping the shield value/percentage display out of the health bar would be better: to modify the health bar means potential conflicts with other mods which also mess it around.
Doesn't even need to be a 'bar', something like the spellbook ring behind the player seems more desirable. Showing cracks on the shield or dimming it maybe?

**Comment by shb201902040125** [comment]
> > Keeping the shield value/percentage display out of the health bar would be better: to modify the health bar means potential conflicts with other mods which also mess it around. Doesn't even need to be a 'bar', something like the spellbook ring behind the player seems more desirable. Showing cracks on the shield or dimming it maybe?
> 
> Actually I dont think the bar over lifebar is necessary .In addition to the reasons you’ve said, it also because it may affect players‘ judgment of their life，but Omni insisted on it.

I think the biggest problem is that your shield value is gold color and the player's life is gold too

**Comment by Felixyang777** [comment]
> > > Keeping the shield value/percentage display out of the health bar would be better: to modify the health bar means potential conflicts with other mods which also mess it around. Doesn't even need to be a 'bar', something like the spellbook ring behind the player seems more desirable. Showing cracks on the shield or dimming it maybe?
> > 
> > 
> > Actually I dont think the bar over lifebar is necessary .In addition to the reasons you’ve said, it also because it may affect players‘ judgment of their life，but Omni insisted on it.
> 
> I think the biggest problem is that your shield value is gold color and the player's life is gold too

That's what I mean

**Comment by Setnour6** [comment]
> > Keeping the shield value/percentage display out of the health bar would be better: to modify the health bar means potential conflicts with other mods which also mess it around. Doesn't even need to be a 'bar', something like the spellbook ring behind the player seems more desirable. Showing cracks on the shield or dimming it maybe?
> 
> Actually I dont think the bar over lifebar is necessary .In addition to the reasons you’ve said, it also because it may affect players‘ judgment of their life，but Omni insisted on it.

Sorry for the late response. You could make a config entry for the health overlay and add a bar beside the player for the amount of time (and shield health) the shield will stay active for before it disappears.

**Comment by Felixyang777** [comment]
> > > Keeping the shield value/percentage display out of the health bar would be better: to modify the health bar means potential conflicts with other mods which also mess it around. Doesn't even need to be a 'bar', something like the spellbook ring behind the player seems more desirable. Showing cracks on the shield or dimming it maybe?
> > 
> > 
> > Actually I dont think the bar over lifebar is necessary .In addition to the reasons you’ve said, it also because it may affect players‘ judgment of their life，but Omni insisted on it.
> 
> Sorry for the late response. You could make a config entry for the health overlay and add a bar beside the player for the amount of time (and shield health) the shield will stay active for before it disappears.

I'll make several different configs for players to choose a few days later.

**Review by Felixyang777 — COMMENTED** [review]
@Omnielement Come and approve the PR，if there is nothing wrong

**Review by Omnielement — APPROVED** [review]

**Pull request merged**
