### PR TITLE
Vortex vanquisher & 3D module

### PR DESCRIPTION
**Pull request by Felixyang777**
这个分支添加了增加了一个新功能，可以支持3D模型在游戏中渲染为射弹或其他东西（比如visual之类的，但我没试过），3Dproj的基类已经写在Everglow\Sources\Everglow.Function\IIID里。
   The branch added a new function which can support 3D model to be rendered in the game as projectile or something else(like visual,but I haven't tried),and the base class of 3Dproj has been writen in Everglow\Sources\Everglow.Function\IIID.

### CODE REVIEW

**Comment by Felixyang777** [comment]
https://github.com/Solaestas/Everglow/assets/104248238/e4e357ad-70cc-42cb-9f9c-51eef49ae4b3

这是演示
Here's the demo

**Review by Setnour6 — CHANGES_REQUESTED** [review]
So I did some testing:
- On the first attack, the player head is always facing or appearing to look down instead of to the cursor. Is that intentional?
- The third and fourth attack also has the player head looking down instead of towards the cursor.
- The right click gold shield is not reducing or blocking damage.
- During the special attack cutscene, the player can get hit multiple times (immunity frame bypass) and can die quickly.

**What needs to change**:
- The player immunity on the cutscene, so the player cannot take damage when they use the Vortex Vanquisher special attack.
- The player head not facing the cursor, unless it is intentional.

Everything else is good.

**Comment by Felixyang777** [comment]
> So I did some testing:
> 
> * On the first attack, the player head is always facing or appearing to look down instead of to the cursor. Is that intentional?
> * The third and fourth attack also has the player head looking down instead of towards the cursor.
> * The right click gold shield is not reducing or blocking damage.
> * During the special attack cutscene, the player can get hit multiple times (immunity frame bypass) and can die quickly.
> 
> **What needs to change**:
> 
> * The player immunity on the cutscene, so the player cannot take damage when they use the Vortex Vanquisher special attack.
> * The player head not facing the cursor, unless it is intentional.
> 
> Everything else is good.

Thank you for your review.
The normal attack has been written long before so I didn't noticed these problems.
But the player's immunity on the cut scene is intentional cuz players may not notice the projectiles from enemies during it.

**Comment by Setnour6** [comment]
I haven't found a fix for the head movement but I edited the immune time so the player does not die during the Planet Befall cutscene. The implementation of 3D modeling and the effects are so good that I also made the weapon a developer item for you!

**Comment by Felixyang777** [comment]
> I haven't found a fix for the head movement but I edited the immune time so the player does not die during the Planet Befall cutscene. The implementation of 3D modeling and the effects are so good that I also made  a developer item for you!
hahaha！Thank u but actually the weapon is originated from genshin impact like Hepuyuan(another weapon),which is omni's request.

**Comment by Setnour6** [comment]
> hahaha！Thank u 😘 but actually the weapon is originated from genshin impact like Hepuyuan(another weapon),which is omni's request.😁😘

Yes, I have known that since it was first added 😁. I might make the tooltip text say "Dedicated" instead of "Developer" but it will still be for you since you made the planet befall attack in the best way possible, or I can keep it as "Developer" if you want

**Comment by Setnour6** [comment]
When I reload the mods list, I get this error message:
image
So that needs to be fixed too.
[client.log](https://github.com/Solaestas/Everglow/files/13707453/client.log) for error

**Comment by Felixyang777** [comment]
> When I reload the mods list, I get this error message: image So that needs to be fixed too. [client.log](https://github.com/Solaestas/Everglow/files/13707453/client.log) for error

Now the bugs may be fixed.
As well as the problem that shield is not reducing or blocking damage.

**Review by Setnour6 — APPROVED** [review]
I find the gold shield working well enough to be approved. There should still be the same effect of the shield disappearing when the player takes enough damage, but that can be done in a future commit. The shield should also be buffed a little bit from '0.23' to '0.33', or any value you think would work well. This is so in master mode and even in hardmode, the player does not lose the shield right after one hit.
Again, I will still approve this. I'm not sure why the item won't appear in the inventory when the player name is Felixyang777 so I could add an item that can then be used to craft the vortex vanquisher easily.

**Pull request merged**
