### PR TITLE
Update ModBuilder Version

### PR DESCRIPTION
**Pull request by Solaestas**
fix configuration missing during building `Everglow.csproj`, which may cause compile failure
I thought this change may prevent project from crashing, but I can't test it

### CODE REVIEW

**Comment by Setnour6** [comment]
I can't test it either. Building the project leads to errors like these:
image

**Comment by Solaestas** [comment]
> I can't test it either. Building the project leads to errors like these: image

I don't know why these errors occur, but I guess that they are blame to VS
Use `dotnet restore`, and then restart VS

**Review by Omnielement — APPROVED** [review]

**Comment by Setnour6** [comment]
The project loading issue may have to do with `<AdditionalFiles Update="**\*.FileListAbsolute.txt" Visible="false" Link="\" />`
image

Removing that line makes the projects load for me.

**Comment by Solaestas** [comment]
> The project loading issue may have to do with `<AdditionalFiles Update="**\*.FileListAbsolute.txt" Visible="false" Link="\" />`
> image
> 
> Removing that line makes the projects load for me.

It's very strange. I add this line just to hide the file named *.FileListAbsolute.txt under obj/.
It should did nothing about building

**Pull request merged**
